import { ApprovalRuleDefinition } from '../types';

export const MASTER_APPROVAL_RULES: ApprovalRuleDefinition[] = [
  // STAGE 1: Land & Site Verification (Days 1 - 25)
  {
    approvalCode: 'APPR_LAND_ALLOT',
    name: 'Industrial Land Allotment & Lease Deed',
    department: 'CSIDC (State Industrial Development Corp)',
    category: 'Land',
    stage: 1,
    slaDays: 20,
    expectedDays: 15,
    isCriticalPath: true,
    parallelGroupId: 'TRACK_LAND',
    requiredDocuments: [
      'Company Incorporation Certificate',
      'PAN & GSTIN Registration',
      'Detailed Project Report (DPR)',
      'Land Requirement Justification',
    ],
    dependencies: [],
  },
  {
    approvalCode: 'APPR_LAND_CONV',
    name: 'Land Use Change & Revenue NOC (Nazul/Agricultural Conversion)',
    department: 'Revenue & Land Records Department',
    category: 'Land',
    stage: 1,
    slaDays: 25,
    expectedDays: 20,
    isCriticalPath: true,
    parallelGroupId: 'TRACK_LAND',
    requiredDocuments: [
      'Land Allotment Order',
      'Revenue Khasra/B1 Map & Records',
      'Site Demarcation Report',
    ],
    dependencies: ['APPR_LAND_ALLOT'],
  },
  {
    approvalCode: 'APPR_SITE_ZONING',
    name: 'Industrial Town & Country Planning (TCP) Zoning NOC',
    department: 'Town and Country Planning Directorate',
    category: 'Land',
    stage: 1,
    slaDays: 18,
    expectedDays: 14,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_LAND',
    requiredDocuments: [
      'Site Layout Master Plan',
      'Zoning Demarcation Certificate',
      'Topographical Survey Drawing',
    ],
    dependencies: ['APPR_LAND_ALLOT'],
  },

  // STAGE 2: Pre-Establishment Clearances (Days 20 - 50)
  {
    approvalCode: 'APPR_POLLUTION_CTE',
    name: 'Consent to Establish (CTE - Orange Category)',
    department: 'Chhattisgarh Environment Conservation Board (CECB)',
    category: 'Environment',
    stage: 2,
    slaDays: 30,
    expectedDays: 22,
    isCriticalPath: true,
    parallelGroupId: 'CRITICAL_TRACK',
    requiredDocuments: [
      'Environmental Management Plan (EMP)',
      'ETP/STP Process Flow Diagram',
      'Detailed Project Report (DPR)',
      'Site Layout with Emissions Stack details',
      'Raw Material & Energy Balance Sheet',
    ],
    dependencies: ['APPR_LAND_CONV'],
  },
  {
    approvalCode: 'APPR_FIRE_PROV',
    name: 'Provisional Fire Safety NOC & Hydrant Design',
    department: 'State Fire & Emergency Services',
    category: 'Safety',
    stage: 2,
    slaDays: 15,
    expectedDays: 12,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_SAFETY',
    requiredDocuments: [
      'Fire Evacuation & Hydrant Layout Plan',
      'Architectural Safety Elevation Plans',
      'Water Reservoir Capacity Proof',
    ],
    dependencies: ['APPR_SITE_ZONING'],
  },
  {
    approvalCode: 'APPR_BLDG_PLAN',
    name: 'Factory Building Plan Approval & Height Sanction',
    department: 'Municipal Corporation / CSIDC Engineering Wing',
    category: 'Municipal',
    stage: 2,
    slaDays: 21,
    expectedDays: 18,
    isCriticalPath: true,
    parallelGroupId: 'CRITICAL_TRACK',
    requiredDocuments: [
      'Architectural Layout & Elevation Drawings (CAD)',
      'Structural Stability Certificate (Vetted Engineer)',
      'Soil Testing & Bearing Capacity Report',
      'Provisional Fire NOC Copy',
    ],
    dependencies: ['APPR_POLLUTION_CTE', 'APPR_FIRE_PROV'],
  },
  {
    approvalCode: 'APPR_WATER_ALLOC',
    name: 'Groundwater / Industrial Water Allocation NOC',
    department: 'Water Resources Department (WRD) / CGWA',
    category: 'Water',
    stage: 2,
    slaDays: 20,
    expectedDays: 15,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_UTILITIES',
    requiredDocuments: [
      'Water Balance Flowchart',
      'Rainwater Harvesting Detailed Scheme',
      'Hydrogeological Survey Report',
    ],
    dependencies: ['APPR_LAND_ALLOT'],
  },
  {
    approvalCode: 'APPR_POWER_FEASIBILITY',
    name: 'HT Power Grid Feasibility & Substation Sanction (250 KW)',
    department: 'CSPDCL (State Power Distribution Co.)',
    category: 'Power',
    stage: 2,
    slaDays: 15,
    expectedDays: 10,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_UTILITIES',
    requiredDocuments: [
      'Connected Load Estimation Sheet',
      'Single Line Electrical Diagram (SLD)',
      'Substation Layout & Transformer Specs',
    ],
    dependencies: ['APPR_LAND_ALLOT'],
  },
  {
    approvalCode: 'APPR_FOREST_NOC',
    name: 'Forest Eco-Sensitive Buffer Zone NOC',
    department: 'State Forest & Wildlife Department',
    category: 'Environment',
    stage: 2,
    slaDays: 30,
    expectedDays: 20,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_ENVIRONMENT',
    requiredDocuments: [
      'GPS Coordinates Map',
      'Distance from Protected Sanctuary Proof',
      'Affidavit on Non-Forest Land',
    ],
    dependencies: ['APPR_LAND_ALLOT'],
  },

  // STAGE 3: Construction & Pre-Operation Approvals (Days 45 - 75)
  {
    approvalCode: 'APPR_DISH_FACTORY',
    name: 'Directorate of Industrial Safety & Health (DISH) Factory Plan Approval',
    department: 'Labour Commissioner & DISH',
    category: 'Safety',
    stage: 3,
    slaDays: 25,
    expectedDays: 20,
    isCriticalPath: true,
    parallelGroupId: 'CRITICAL_TRACK',
    requiredDocuments: [
      'Approved Building Layout Plan',
      'Machinery Layout & Clear Passage Map',
      'Health Hazard & Safety Ventilation Plan',
      'Form No. 1 (Factories Act 1948)',
    ],
    dependencies: ['APPR_BLDG_PLAN'],
  },
  {
    approvalCode: 'APPR_ELECTRICAL_INSPECTION',
    name: 'Chief Electrical Inspectorate (CEIG) Safety Clearance',
    department: 'Chief Electrical Inspectorate, Energy Dept',
    category: 'Power',
    stage: 3,
    slaDays: 14,
    expectedDays: 10,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_UTILITIES',
    requiredDocuments: [
      'Earthing & Insulation Test Reports',
      'Transformer & DG Set Installation Certificate',
      'CEIG Inspection Application Form',
    ],
    dependencies: ['APPR_POWER_FEASIBILITY'],
  },
  {
    approvalCode: 'APPR_BOILER_REG',
    name: 'Industrial Boiler Registration & Steam Pipeline Inspection',
    department: 'Directorate of Boilers',
    category: 'Safety',
    stage: 3,
    slaDays: 18,
    expectedDays: 14,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_SAFETY',
    requiredDocuments: [
      'Boiler Manufacturer Quality Certificate (Form II/III)',
      'Steam Pipe Layout Drawing',
      'Boiler Attendant Competency Certificate',
    ],
    dependencies: ['APPR_BLDG_PLAN'],
  },
  {
    approvalCode: 'APPR_EXPLOSIVE_PESO',
    name: 'PESO License for Gas Storage / Fuel Storage Facility',
    department: 'Petroleum and Explosives Safety Organization',
    category: 'Safety',
    stage: 3,
    slaDays: 30,
    expectedDays: 24,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_SAFETY',
    requiredDocuments: [
      'Safety Distance Demarcation Drawing',
      'Tank Fabrication Certificate',
      'Fire Fighting Network Layout',
    ],
    dependencies: ['APPR_FIRE_PROV', 'APPR_BLDG_PLAN'],
  },

  // STAGE 4: Final Consent to Operate & Licensing (Days 65 - 90)
  {
    approvalCode: 'APPR_POLLUTION_CTO',
    name: 'Consent to Operate (CTO) under Air & Water Acts',
    department: 'Chhattisgarh Environment Conservation Board (CECB)',
    category: 'Environment',
    stage: 4,
    slaDays: 30,
    expectedDays: 20,
    isCriticalPath: true,
    parallelGroupId: 'CRITICAL_TRACK',
    requiredDocuments: [
      'CTE Compliance Report & Photos',
      'ETP/STP Commissioning & Test Reports',
      'Stack Emission & Noise Monitoring Report',
      'Solid/Hazardous Waste Storage Manifest',
    ],
    dependencies: ['APPR_POLLUTION_CTE', 'APPR_DISH_FACTORY'],
  },
  {
    approvalCode: 'APPR_FIRE_FINAL',
    name: 'Final Fire Safety Occupancy Certificate',
    department: 'State Fire & Emergency Services',
    category: 'Safety',
    stage: 4,
    slaDays: 14,
    expectedDays: 10,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_SAFETY',
    requiredDocuments: [
      'Provisional Fire NOC Compliance Report',
      'Hydrant & Sprinkler Flow Test Records',
      'Fire Training & Drill Logbook',
    ],
    dependencies: ['APPR_FIRE_PROV', 'APPR_BLDG_PLAN'],
  },
  {
    approvalCode: 'APPR_FSSAI_MFG',
    name: 'FSSAI Central / State Manufacturing License',
    department: 'Food Safety and Standards Authority of India (FSSAI)',
    category: 'Operating',
    stage: 4,
    slaDays: 21,
    expectedDays: 15,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_OPERATING',
    requiredDocuments: [
      'Food Safety Management System (FSMS) Plan',
      'Water Potability Lab Test Report (IS 10500)',
      'Equipment Layout & Processing Capacity Flow',
      'List of Food Categorization & Technical Staff',
    ],
    dependencies: ['APPR_POLLUTION_CTO'],
    condition: (p) => p.sector.toLowerCase().includes('food'),
  },
  {
    approvalCode: 'APPR_LEGAL_METROLOGY',
    name: 'Legal Metrology Packaging & Weight Verification License',
    department: 'Department of Consumer Affairs / Legal Metrology',
    category: 'Operating',
    stage: 4,
    slaDays: 15,
    expectedDays: 10,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_OPERATING',
    requiredDocuments: [
      'Sample Product Label Specimen',
      'Weighing Machine Calibration Certificate',
      'Director/Partner KYC Documents',
    ],
    dependencies: ['APPR_DISH_FACTORY'],
  },
  {
    approvalCode: 'APPR_POWER_HT_CONNECTION',
    name: 'Permanent HT Electricity Metering & Energization (11KV/33KV)',
    department: 'CSPDCL (Power Utility)',
    category: 'Power',
    stage: 4,
    slaDays: 10,
    expectedDays: 7,
    isCriticalPath: false,
    parallelGroupId: 'TRACK_UTILITIES',
    requiredDocuments: [
      'CEIG Safety Clearance Certificate',
      'Power Agreement & Security Deposit Receipt',
      'Meter Testing & Verification Certificate',
    ],
    dependencies: ['APPR_ELECTRICAL_INSPECTION'],
  },
];
